### ISSUE TITLE
MVPリリースレビュー用issue

### ISSUE THREAD

**Issue by 2bs2bs** [2bs2bs/syukan_meter#132]
## 各種情報
syukan-meter
https://syukan-meter-a3b4e7eb43a0.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ポモドーロタイマー機能
- [x] ログイン機能
- [x] いいね機能
- [x] コメント機能
- [x] 投稿機能
- [x] カレンダー機能
- [x] モーダル機能
- [x] ユーザー登録機能
- [x] 習慣登録、編集機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## READMEレビュー時から変更した機能
- [ ] リマインダー機能
- [ ] ハンバーガーメニュー機能
- [ ] 通知機能
- [ ] パスワード変更機能

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
上記にある`モーダル機能`というのはどのような操作を行えば挙動確認ができるかを説明していただけますか。

**Comment by 2bs2bs** [comment]
レビュー返答ありがとうございます！
モーダル機能は投稿作成、コメント作成、習慣作成でページ遷移せずフォームが表示されるようにしたもののことです。

**Comment by Tsuchiya2** [comment]
> モーダル機能は投稿作成、コメント作成、習慣作成でページ遷移せずフォームが表示されるようにしたもののことです。

それはモーダルではない気がしますね。モーダルと聞くと以下にあるようにページの上に表示されるものという認識が一般的かと思います。どういったことをしたかったのか整理して見るべきポイントを提示していただけますか。

https://www.sedesign.co.jp/blog/what-is-modal-window

**Comment by 2bs2bs** [comment]
失礼しました！
フォーム入力の際画面遷移して欲しくないというイメージで行なっていました

**Comment by Tsuchiya2** [comment]
上記理解しました。
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
