### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by 2bs2bs** [2bs2bs/syukan_meter#19]
概要

### 実装予定の機能
- [ ] 通知機能
- [ ] リマンダー機能
- [x] ポモドーロタイマー機能
- [x] ログイン機能
- [x] いいね機能
- [x] コメント機能
- [x] 投稿機能
- [ ] パスワード変更機能
- [x] カレンダー機能
- [x] モーダル機能
- [x] ユーザー登録機能
- [x] 習慣登録、編集機能
- [ ] ハンバーガーメニュー機能

### 必要なページ

- [x] スタートページ
- [ ] ログインページ
- [ ] ユーザー登録ページ
- [ ] パスワードリセットページ
- [ ] パスワードリセットメール
- [ ] ホームページ(ログイン後のスタート画面)
- [ ] タイマーページ
- [ ] 習慣詳細ページ
- [ ] 習慣作成、編集ページ(モーダル表示)
- [ ] カレンダーページ
- [ ] 投稿一覧ページ
- [ ] 投稿作成＆編集ページ(モーダル表示)
- [ ] 投稿詳細ページ、ユーザー詳細ページ(モーダル表示)
- [ ] プロフィールページ
- [ ] プロフィール編集ページ(モーダル表示)
- 共通
- [ ] ナビゲーションバー
- [ ] ハンバーガーメニュー
- [ ] 共通ページ(layout/application)作成

**Comment by Tsuchiya2** [comment]
![スクリーンショット 2023-12-24 13 59 05](https://github.com/2bs2bs/syukan_meter/assets/61481161/04a8f22c-3842-4880-b5fc-daab1310c0f5)

projectタブをクリックしましたが、看板・Issue・ストーリーポイントの確認ができませんでした。
確認できる状態にして再提出をお願いいたします。

**Comment by Tsuchiya2** [comment]
確認しました。
ストーリーポイント５が多いですので、もう少し細かくIssue立てしましょう。
細かくすることで何を行うのかが明確化しますし、進捗を感じながら開発を進めることができます。

**Comment by 2bs2bs** [comment]
失礼いたしました！プロジェクトをプライベートにしてしまっていたので公開に変更いたしました！

**Comment by 2bs2bs** [comment]
レビューありがとうございます！
もう少し細分化して再度提出いたします！

**Comment by 2bs2bs** [comment]
ありがとうございます！！！頑張ります！！！
